site_name: PGDL Lexer for Pygments


theme:
    name: material


markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.superfences

    
repo_url: https://github.com/luelista/pygments-pgdl-lexer
