site_name: PGDL Lexer for Pygments
site_url: https://luelista.github.io/pygments-pgdl-lexer/

theme:
    name: material
    font: false
extra_css:
    - style/style.css


markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.superfences

    
repo_url: https://github.com/luelista/pygments-pgdl-lexer
